#cloud-config

bootcmd:
  - DEBIAN_FRONTEND=noninteractive apt-get -yq update
  - DEBIAN_FRONTEND=noninteractive apt-get -yq install gnupg
  - mkdir -p /etc/logrotate.d # needs to exist before write_files runs

apt:
  conf: |
    APT {
      Get {
        Assume-Yes "true";
        Fix-Broken "true";
      };
    };

packages:
  - awscli
  - git
  - logrotate
  - unattended-upgrades
package_upgrade: true

runcmd:
  - echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure unattended-upgrades
  - sysctl -p /etc/sysctl.d/50-tcp_bbr.conf
  - sudo -u ubuntu git clone https://github.com/alecmuffett/eotk.git /home/ubuntu/eotk
  - cd /home/ubuntu/eotk ; sudo -u ubuntu ./opt.d/build-ubuntu-20.04.sh

write_files:
  - content: ${logrotate_script}
    path: /etc/logrotate.d/eotk
    owner: root:root
    permissions: '0644'
  - content: ${crontab}
    path: /etc/cron.d/eotk
    owner: root:root
    permissions: '0644'
  - content: |
      net.core.default_qdisc=fq
      net.ipv4.tcp_congestion_control=bbr
    path: /etc/sysctl.d/50-tcp_bbr.conf
    owner: root:root
    permissions: '0644'
